faiss_db:
  collection_name: "documument_portal"

embedding_model:
  provider: "google"
  #model_name: "models/text-embedding-004"
  #model_name: "models/embedding-001"
  model_name: "models/gemini-embedding-001"
  #model_name: "models/multilingual-e5-large"
  
retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    #model_name: "deepseek-r1-distill-llama-70b"
    model_name: "llama-3.1-8b-instant"
    #temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
